package oprpp2.hw01.message;

import oprpp2.hw01.enums.MessageType;

/**
 * This class represent message for establishing connection with server
 *
 * @author Dean Trkulja
 * @version 1.0
 */
public class HelloMessage extends Message {
    /**
     * Rendom key generated by {@link oprpp2.hw01.client.Client}
     */
    private final long key;
    /**
     * Name of client
     */
    private final String name;

    /**
     * Creates an instance of {@code HelloMessage}
     * @param messageId id of message
     * @param name name of client
     * @param key random key generated by client
     */
    public HelloMessage(long messageId, String name,long key) {
        super(MessageType.HELLO, messageId);
        this.key = key;
        this.name = name;
    }

    /**
     * Getter for key.
     *
     * @return key
     */

    public long getKey() {
        return key;
    }

    /**
     * Getter for name of client
     * @return client name
     */
    public String getName() {
        return name;
    }
}
